apiVersion: apps/v1
kind: Deployment
metadata:
  name: asia
  namespace: world
  labels:
    app: asia
spec:
  replicas: 2
  selector:
    matchLabels:
      app: asia
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  template:
    metadata:
      labels:
        app: asia
    spec:
      initContainers:
        - name: init-container
          image: busybox:1.28
          command: ["sh", "-c", "echo 'hello, you reached ASIA' > /html/index.html"]
          volumeMounts:
            - name: html
              mountPath: /html
      containers:
        - name: c
          image: nginx:1.21.5-alpine
          volumeMounts:
            - name: nginx-conf
              mountPath: /etc/nginx
              readOnly: true
            - name: html
              mountPath: /usr/share/nginx/html
      volumes:
        - name: html
          emptyDir: {}
        - name: nginx-conf
          configMap:
            name: nginx-conf
            optional: false
