apiVersion: v1
kind: Service
metadata:
  name: europe
  namespace: world
  labels:
    app: europe
spec:
  type: ClusterIP
  selector:
    app: europe
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
