apiVersion: v1
kind: Service
metadata:
  name: asia
  namespace: world
  labels:
    app: asia
spec:
  type: ClusterIP
  selector:
    app: asia
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
