apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: world-tls-dns
  namespace: world
spec:
  secretName: world-tls-dns
  issuerRef:
    name: letsencrypt-dns
    kind: ClusterIssuer
  commonName: world.rmeservicesllc.com
  dnsNames:
    - world.rmeservicesllc.com
