apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: world-tls-letsencrypt
  namespace: world
spec:
  secretName: world-tls-letsencrypt
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: world.rmeservicesllc.com
  dnsNames:
    - world.rmeservicesllc.com
